### ISSUE TITLE
执行出错Cannot find module 'ejs'怎么破？

### ISSUE THREAD

**Issue by starjason** [linfuyan/demo-cheerio-ejs#1]
执行 node index.js 
报错：
module.js:327
    throw err;
    ^

Error: Cannot find module 'ejs'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/demo-cheerio-ejs/index.js:3:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

**Comment by linfuyan** [comment]
上面问题是因为没有安装ejs模块依赖导致的。在项目根目录下面，需要先执行 npm install，这样会根据 package.json 的配置安装 ejs 模块，然后再执行 node.index.js。

**Comment by starjason** [comment]
npm install
npm WARN package.json demo-cheerio-ejs@1.0.0 No repository field.

**Comment by linfuyan** [comment]
也可能是你的 ejs 模块由于网络原因没有安装完整。
这边你可以尝试把根目录下面的 node_modules 目录删除，然后再 npm install 一下。

不过现在index.js里面的 http://ss.upgrommer.cn 地址无法访问了，需要 https://ss.upgrommer.cn 才可以，所以 node index.js 应该也跑不起来，需要修改下。

**Comment by starjason** [comment]
地址是： http://ss.upgrommer.cn时  执行node index.js 报错：
`events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: read ECONNRESET
    at errnoException (net.js:901:11)
    at TCP.onread (net.js:556:19)`
地址是：https://ss.upgrommer.cn时，执行node index.js 报错：
`http.js:1840
    throw new Error('Protocol:' + options.protocol + ' not supported.');
          ^
Error: Protocol:https: not supported.
    at Object.exports.request (http.js:1840:11)
    at Object.exports.get (http.js:1847:21)
    at download (/home/ubuntu/demo-cheerio-ejs/index.js:7:7)
    at Object.<anonymous> (/home/ubuntu/demo-cheerio-ejs/index.js:34:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)`
